services:
  app-historyserver:
    container_name: app-historyserver
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: bde2020/hadoop-app-historyserver:self-dev
    ports:
    - 8188:8188
    - ${APPLICATION_HISTORYSERVER_DEBUG:-9995}:9999
    restart: always
    volumes:
    - hadoop_historyserver:/hadoop/yarn/timeline
    - test=/opt/hadoop
  datanode:
    container_name: datanode
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: bde2020/hadoop-datanode:self-dev
    ports: null
    restart: always
    volumes:
    - hadoop_datanode:/hadoop/dfs/data
    - test=/opt/hadoop
  job-historyserver:
    container_name: job-historyserver
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: bde2020/hadoop-job-historyserver:self-dev
    ports:
    - 19888:19888
    - ${JOB_HISTORYSERVER_DEBUG:-9994}:9999
    restart: always
    volumes:
    - hadoop_historyserver:/hadoop/yarn/timeline
    - test=/opt/hadoop
  namenode:
    container_name: namenode
    env_file:
    - ./hadoop.env
    environment:
    - CLUSTER_NAME=test
    image: bde2020/hadoop-namenode:self-dev
    ports:
    - 9870:9870
    - 9000:9000
    restart: always
    volumes:
    - hadoop_namenode:/hadoop/dfs/name
    - test=/opt/hadoop
  nodemanager1:
    container_name: nodemanager
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: bde2020/hadoop-nodemanager:self-dev
    ports:
    - 8042:8042
    - ${NODEMANAGER_DEBUG:-9998}:9999
    restart: always
    volumes:
    - test=/opt/hadoop
  nodemanager2:
    container_name: nodemanager2
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: bde2020/hadoop-nodemanager:self-dev
    ports:
    - 8043:8042
    - ${NODEMANAGER2_DEBUG:-9997}:9999
    restart: always
    volumes:
    - test=/opt/hadoop
  nodemanager3:
    container_name: nodemanager3
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: bde2020/hadoop-nodemanager:self-dev
    ports:
    - 8044:8042
    - ${NODEMANAGER3_DEBUG:-9996}:9999
    restart: always
    volumes:
    - test=/opt/hadoop
  resourcemanager:
    container_name: resourcemanager
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: bde2020/hadoop-resourcemanager:self-dev
    ports:
    - 8088:8088
    - ${RESOURCEMANAGER_DEBUG:-9999}:9999
    - 8032:8032
    restart: always
    volumes:
    - test=/opt/hadoop
version: '3'
volumes:
  hadoop_datanode: null
  hadoop_historyserver: null
  hadoop_namenode: null
