services:
  app-historyserver:
    command:
    - /run.sh
    container_name: app-historyserver
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: hadock/hadoop-app-historyserver:mount
    ports:
    - 8188:8188
    - ${APPLICATION_HISTORYSERVER_DEBUG:-9995}:9999
    restart: always
    volumes:
    - hadoop_historyserver:/hadoop/yarn/timeline
    - /Users/andrasgyori/Programming/upstream/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT:/opt/hadoop
  datanode:
    command:
    - /run.sh
    container_name: datanode
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: hadock/hadoop-datanode:mount
    ports: []
    restart: always
    volumes:
    - hadoop_datanode:/hadoop/dfs/data
    - /Users/andrasgyori/Programming/upstream/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT:/opt/hadoop
  job-historyserver:
    command:
    - /run.sh
    container_name: job-historyserver
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: hadock/hadoop-job-historyserver:mount
    ports:
    - 19888:19888
    - ${JOB_HISTORYSERVER_DEBUG:-9994}:9999
    restart: always
    volumes:
    - hadoop_historyserver:/hadoop/yarn/timeline
    - /Users/andrasgyori/Programming/upstream/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT:/opt/hadoop
  namenode:
    command:
    - /run.sh
    container_name: namenode
    env_file:
    - ./hadoop.env
    environment:
    - CLUSTER_NAME=test
    image: hadock/hadoop-namenode:mount
    ports:
    - 9870:9870
    - 9000:9000
    restart: always
    volumes:
    - hadoop_namenode:/hadoop/dfs/name
    - /Users/andrasgyori/Programming/upstream/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT:/opt/hadoop
  nodemanager1:
    command:
    - /run.sh
    container_name: nodemanager
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: hadock/hadoop-nodemanager:mount
    ports:
    - 8042:8042
    - ${NODEMANAGER_DEBUG:-9998}:9999
    restart: always
    volumes:
    - /Users/andrasgyori/Programming/upstream/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT:/opt/hadoop
  nodemanager2:
    command:
    - /run.sh
    container_name: nodemanager2
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: hadock/hadoop-nodemanager:mount
    ports:
    - 8043:8042
    - ${NODEMANAGER2_DEBUG:-9997}:9999
    restart: always
    volumes:
    - /Users/andrasgyori/Programming/upstream/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT:/opt/hadoop
  nodemanager3:
    command:
    - /run.sh
    container_name: nodemanager3
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: hadock/hadoop-nodemanager:mount
    ports:
    - 8044:8042
    - ${NODEMANAGER3_DEBUG:-9996}:9999
    restart: always
    volumes:
    - /Users/andrasgyori/Programming/upstream/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT:/opt/hadoop
  resourcemanager:
    command:
    - /run.sh
    container_name: resourcemanager
    env_file:
    - ./hadoop.env
    environment:
    - SERVICE_PRECONDITION
    image: hadock/hadoop-resourcemanager:mount
    ports:
    - 8088:8088
    - ${RESOURCEMANAGER_DEBUG:-9999}:9999
    - 8032:8032
    restart: always
    volumes:
    - /Users/andrasgyori/Programming/upstream/hadoop/hadoop-dist/target/hadoop-3.4.0-SNAPSHOT:/opt/hadoop
version: '3'
volumes:
  hadoop_datanode: null
  hadoop_historyserver: null
  hadoop_namenode: null
